### ISSUE TITLE
VeRi dataset weights; ValueError: Checkpoint is missing variable [ball/beta]

### ISSUE THREAD

**Issue by david-schweitzer** [nwojke/deep_sort#174]
I used the cosine metric learning repository you made to train on the VeRi dataset, and I used the command provided to create a PB graph.  Putting the four files in the resources/networks folder (.pb, .meta, .index, and .data-00000-of-00001), I run into the following error (ignore the ??? in my pc account name; I manually edited that):

WARNING:tensorflow:From C:\Users\???\Desktop\track\deep_sort\generate_detections.py:176: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From C:\Users\???\Desktop\track\deep_sort\generate_detections.py:320: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    tfnet.camera()
  File "C:\Users\???\Desktop\track\darkflow\darkflow\net\help.py", line 83, in camera
    os.path.abspath("deep_sort/resources/networks/mars-small128.ckpt-68577"))
  File "C:\Users\???\Desktop\track\deep_sort\generate_detections.py", line 348, in create_box_encoder
    image_encoder = create_image_encoder(model_filename, batch_size, loss_mode)
  File "C:\Users\???\Desktop\track\deep_sort\generate_detections.py", line 343, in create_image_encoder
    model_filename, loss_mode)
  File "C:\Users\???\Desktop\track\deep_sort\generate_detections.py", line 322, in _create_image_encoder
    checkpoint_path, slim.get_variables_to_restore())
  File "C:\Users\???\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 671, in assign_from_checkpoint
    raise ValueError(log_str)
ValueError: Checkpoint is missing variable [ball/beta]

**Comment by YachaoDong** [comment]
Hello, how to train the VeRi dataset?  Which .py file is used for training the VeRi dataset? Thank you very muchhhh!!

**Comment by a0981456759** [comment]
Hello, did you solve the problem? Could you share your model? thank you very much!
