### ISSUE TITLE
freeze_model.py Error: FindFirstFile failed ... No such process

### ISSUE THREAD

**Issue by pipidoudou** [nwojke/deep_sort#178]
same problem with  https://github.com/nwojke/deep_sort/issues/80. But the solution didn't work.

I got the same error when running freeze_model.py on Windows 10:

Traceback (most recent call last):
File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in 
main()
File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "D:/work/chelun/tools/freeze_model.py", line 219, in 
main()
File "D:/work/chelun/tools/freeze_model.py", line 209, in main
saver.restore(session, args.checkpoint_in)
File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1536, in restore
if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 364, in checkpoint_exists
if file_io.get_matching_files(pathname):
File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
for single_filename in filename
File "D:\work\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: resources/networks : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

But I ran generate_directions.py successfully.

I tried to change the path in the code to absolute path . But no matter "D:/xx/xx" or "D:\xx\xx", still failed.

parser.add_argument(
"--checkpoint_in",
default="resources/networks/mars-small128.ckpt-68577",
help="Path to checkpoint file")
parser.add_argument(
"--graphdef_out",
default="resources/networks/mars-small128.pb")

Can you help me fix this error? Thank you.

**Comment by leezisheng** [comment]
i meet the same problem, do you fix it?
