### ISSUE TITLE
Module Error?

### ISSUE THREAD

**Issue by AegonLin** [nwojke/deep_sort#208]
When I execute "python deep_sort_app.py -h" in cmd
error is "Traceback (most recent call last):
  File "deep_sort_app.py", line 14, in <module>
    from deep_sort.tracker import Tracker
  File "C:\Users\user\Downloads\deep_sort-master\deep_sort\tracker.py", line 5, in <module>
    from . import linear_assignment
  File "C:\Users\user\Downloads\deep_sort-master\deep_sort\linear_assignment.py", line 4, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_"

**Comment by honeyshine75** [comment]
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
DeprecationWarning)

so you should reinstall a lower  sklearn

**Comment by xingkongliang** [comment]
from scipy.optimize import linear_sum_assignment as linear_assignment
