### ISSUE TITLE
Could someone kindly offer versions number of dependecies which is tested on?

### ISSUE THREAD

**Issue by WorstCodeWay** [nwojke/deep_sort#227]
I don't know what versions of dependencies, so I install all the latest versions of those dependencies and something wrong seems to complain. I don't know if that error is related to versions.

So, would anyone tell the tested dependencies versions? Like:
```
tensorflow-gpu==2.1.0??
sklearn==??
opencv-python==??
```
Currently, I meet two error and one of it has been discussed here and the other one is:
```
(venv) lihuawei@svision:deep_sort$ python deep_sort_app.py --sequence_dir=MOT16/test/MOT16-06 --detection_file=resources/detections/MOT16_POI_test/MOT16-06.npy --min_confidence=0.3 --nn_budget=100 --display=True
Processing frame 00001
Processing frame 00002
Traceback (most recent call last):
  File "deep_sort_app.py", line 263, in <module>
    args.max_cosine_distance, args.nn_budget, args.display)
  File "deep_sort_app.py", line 206, in run
    visualizer.run(frame_callback)
  File "/home/lihuawei/Documents/01_Gits/deep_sort/application_util/visualization.py", line 100, in run
    self.viewer.run(lambda: self._update_fun(frame_callback))
  File "/home/lihuawei/Documents/01_Gits/deep_sort/application_util/image_viewer.py", line 305, in run
    self._terminate = not self._user_fun()
  File "/home/lihuawei/Documents/01_Gits/deep_sort/application_util/visualization.py", line 100, in <lambda>
    self.viewer.run(lambda: self._update_fun(frame_callback))
  File "/home/lihuawei/Documents/01_Gits/deep_sort/application_util/visualization.py", line 105, in _update_fun
    frame_callback(self, self.frame_idx)
  File "deep_sort_app.py", line 183, in frame_callback
    tracker.update(detections)
  File "/home/lihuawei/Documents/01_Gits/deep_sort/deep_sort/tracker.py", line 69, in update
    self._match(detections)
  File "/home/lihuawei/Documents/01_Gits/deep_sort/deep_sort/tracker.py", line 127, in _match
    detections, iou_track_candidates, unmatched_detections)
  File "/home/lihuawei/Documents/01_Gits/deep_sort/deep_sort/linear_assignment.py", line 63, in min_cost_matching
    if col not in indices[:, 1]:
TypeError: tuple indices must be integers or slices, not tuple
```
Thanks, in advance.

**Comment by WorstCodeWay** [comment]
After some tests, I give my configurations of dependencies:
```
absl-py==0.10.0
astor==0.8.1
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
gast==0.2.2
google-auth==1.21.3
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
importlib-metadata==2.0.0
joblib==0.16.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.2.2
numpy==1.19.2
oauthlib==3.1.0
opencv-python==4.4.0.44
opt-einsum==3.3.0
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.20.0
scipy==1.4.1
six==1.15.0
sklearn==0.0
tensorboard==2.1.1
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
termcolor==1.1.0
threadpoolctl==2.1.0
urllib3==1.25.10
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.2.0
```
Basically, `Tensorflow-gpu==2.1.0` and `scikit-learn==0.20.0` works for me.


Besides, tried other combinations, such as with `scikit-learn==0.23.2`, get execution error, with tensorflow-gpu==1.0, the video is zoom in gradually.

**Comment by iamZe** [comment]
you saved my day! thanks
