### ISSUE TITLE
cannot connect to xserver in google colab

### ISSUE THREAD

**Issue by Gour8606** [nwojke/deep_sort#250]
while running the below codein google colab it shows error : cannot connect to x server 

! python3 deep_sort/deep_sort_app.py \
--sequence_dir=./deep_sort/MOT16/test/MOT16-06 \
--detection_file=./deep_sort/resources/detections/MOT16_POI_test/MOT16-06.npy \
--min_confidence=0.3 \
--nn_budget=100 \
--display=True

**Comment by RizwanAliQau** [comment]
write 
-- display=False

**Comment by MsAnitaAli** [comment]
@RizwanAliQau  thanks, but it processes first frame, displays nothing and on second frame of all file folders, it displays this error

Processing frame 00001
Processing frame 00002
Traceback (most recent call last):
  File "/content/drive/My Drive/deep_sort/deep_sort_app.py", line 261, in <module>
    run(
  File "/content/drive/My Drive/deep_sort/deep_sort_app.py", line 207, in run
    visualizer.run(frame_callback)
  File "/content/drive/My Drive/deep_sort/application_util/visualization.py", line 80, in run
    frame_callback(self, self.frame_idx)
  File "/content/drive/My Drive/deep_sort/deep_sort_app.py", line 184, in frame_callback
    tracker.update(detections)
  File "/content/drive/My Drive/deep_sort/deep_sort/tracker.py", line 69, in update
    self._match(detections)
  File "/content/drive/My Drive/deep_sort/deep_sort/tracker.py", line 125, in _match
    linear_assignment.min_cost_matching(
  File "/content/drive/My Drive/deep_sort/deep_sort/linear_assignment.py", line 63, in min_cost_matching
    if col not in indices[:, 1]:
TypeError: tuple indices must be integers or slices, not tuple

**Now what to do?**
