### ISSUE TITLE
"steps" argument being passed as None

### ISSUE THREAD

**Issue by nipun1992** [nwojke/deep_sort#298]
When using the yolo.predict() function, there is an exception being returned saying that "steps" argument needs to be specified. In the method implementations, the steps argument has been set to None and this parameter is not being set in the method invocation. Is there any need or is it mandatory to specify the steps argument in yolo.predict() function?

Also, when trying to search for the steps argument in the predict() function, the search does not return this argument upon looking for it in pycharm.

Please suggest. Thank you.

**Comment by nipun1992** [comment]
Exception details:

Traceback (most recent call last):
  File "C:/Users/nipun.gupta/Downloads/UniquePersonDeepSort/src/testDeepSort.py", line 16, in <module>
    output = predictImage(req)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSort\src\getImagePredictionDeepSort.py", line 134, in predictImage
    boxes, scores, classes, nums = yolo.predict(img_in)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSort\venv\lib\site-packages\keras\engine\training_v1.py", line 978, in predict
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSort\venv\lib\site-packages\keras\engine\training_arrays_v1.py", line 699, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSort\venv\lib\site-packages\keras\engine\training_v1.py", line 2288, in _standardize_user_data
    training_utils_v1.check_steps_argument(x, steps, steps_name)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSort\venv\lib\site-packages\keras\engine\training_utils_v1.py", line 1317, in check_steps_argument
    input_type=input_type_str, steps_name=steps_name))
ValueError: When using data tensors as input to a model, you should specify the `steps` argument.
