### ISSUE TITLE
Error when generating detections

### ISSUE THREAD

**Issue by nvnnghia** [nwojke/deep_sort#64]
Hi, Thank for sharing the code. When I tried to regenerate detections (.npy files). I got error. So I think it's because my tf vesion (1.3.0) is different from yours. Therefore, I re-exported the frozen inference graph, but I got error like this 
`python tools/freeze_model.py 
2018-04-17 17:27:29.145297: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] ARM64 does not support NUMA - returning NUMA node zero
2018-04-17 17:27:29.145415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: NVIDIA Tegra X2
major: 6 minor: 2 memoryClockRate (GHz) 1.3005
pciBusID 0000:00:00.0
Total memory: 7.67GiB
Free memory: 3.96GiB
2018-04-17 17:27:29.145469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-04-17 17:27:29.145494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-04-17 17:27:29.145520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0)
Traceback (most recent call last):
  File "tools/freeze_model.py", line 219, in <module>
    main()
  File "tools/freeze_model.py", line 205, in main
    features, _ = factory_fn(image_var, reuse=None)
  File "tools/freeze_model.py", line 169, in factory_fn
    image, reuse=reuse, weight_decay=weight_decay)
  File "tools/freeze_model.py", line 155, in _create_network
    tf.reduce_sum(tf.square(features), [1], keepdims=True))
TypeError: reduce_sum() got an unexpected keyword argument 'keepdims'
`
do you have any suggestion? Thank you

**Comment by nwojke** [comment]
Which version of TensorFlow are you using? Alternatively, change ``keepdims=`` to ``keep_dims=`` in line 155 of freeze_model.py

**Comment by nvnnghia** [comment]
It worked. Thank you.

**Comment by nvnnghia** [comment]
Now, I can re-export the frozen inference graph. But When I tried to regenerate detections (.npy files). I got error. 
`2018-04-23** 15:13:28.160325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: NVIDIA Tegra X2
major: 6 minor: 2 memoryClockRate (GHz) 1.3005
pciBusID 0000:00:00.0
Total memory: 7.67GiB
Free memory: 4.74GiB
2018-04-23 15:13:28.160377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-04-23 15:13:28.160401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-04-23 15:13:28.160427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0)
('count', 5)
nvidia@tegra-ubuntu:~/realtime_object_detection$ python testtrak.py 
2018-04-23 15:13:59.212171: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:857] ARM64 does not support NUMA - returning NUMA node zero
2018-04-23 15:13:59.212290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: NVIDIA Tegra X2
major: 6 minor: 2 memoryClockRate (GHz) 1.3005
pciBusID 0000:00:00.0
Total memory: 7.67GiB
Free memory: 4.74GiB
2018-04-23 15:13:59.212347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-04-23 15:13:59.212370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-04-23 15:13:59.212408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0)
('count', 5)
2018-04-23 15:14:04.930646: E tensorflow/stream_executor/cuda/cuda_driver.cc:1068] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_FAILED
2018-04-23 15:14:04.930722: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0x28a1d10: CUDA_ERROR_LAUNCH_FAILED
2018-04-23 15:14:04.930754: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x28a1d10: CUDA_ERROR_LAUNCH_FAILED
2018-04-23 15:14:04.930919: F tensorflow/stream_executor/cuda/cuda_dnn.cc:2045] failed to enqueue convolution on stream: CUDNN_STATUS_EXECUTION_FAILED
Aborted (core dumped)
`

I reboot my jetsontx2, when I first time run the code, the error is gone . From the second time, the error happened again. Any suggestion??
