### ISSUE TITLE
Problem running the generate_videos.py   

### ISSUE THREAD

**Issue by ifahim** [nwojke/deep_sort#68]
I am trying to run the following command but keeps on getting the error. 
Can anyone confirm if the command sequence is correct?  

`$ python show_results.py --sequence_dir=./MOT16/train/MOT16-02/ --detection_file=./deep_sort_data/resources/detections/MOT16_POI_train/MOT16-02.npy --result_file=./MOT16/train/MOT16-02/gt/gt.txt --output_file=./outputdir/delnow.avi`

````
Frame idx 1
[912. 484.  97. 109.]
Traceback (most recent call last):
  File "show_results.py", line 113, in <module>
    args.detection_file, args.update_ms, args.output_file)
  File "show_results.py", line 80, in run
    visualizer.run(frame_callback)
  File "/home/user/scripts/deep_sort/application_util/visualization.py", line 100, in run
    self.viewer.run(lambda: self._update_fun(frame_callback))
  File "/home/user/scripts/deep_sort/application_util/image_viewer.py", line 305, in run
    self._terminate = not self._user_fun()
  File "/home/user/scripts/deep_sort/application_util/visualization.py", line 100, in <lambda>
    self.viewer.run(lambda: self._update_fun(frame_callback))
  File "/home/user/scripts/deep_sort/application_util/visualization.py", line 105, in _update_fun
    frame_callback(self, self.frame_idx)
  File "show_results.py", line 58, in frame_callback
    vis.draw_groundtruth(track_ids, boxes)
  File "/home/user/scripts/deep_sort/application_util/visualization.py", line 117, in draw_groundtruth
    self.viewer.rectangle(*box.astype(np.int), 20, label=str(track_id))
TypeError: rectangle() got multiple values for argument 'label'

```
1. Is the `mot_dir` and `result_dir` path correct? An example command would be useful. 
2. I don't see any video output generated in the `outdir` folder

**Comment by nwojke** [comment]
Did you solve this? Looking at the definition of the function which is causing the error [here](https://github.com/nwojke/deep_sort/blob/master/application_util/image_viewer.py#L124): Can you try to remove the 20 from visualization.py:117?

**Comment by nwojke** [comment]
I am closing this issue due to inactivity. Re-open if the problem persists.
